module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Tasks', [{
      task_type: 'personal',
      title: 'Ведомости',
      content: 'Заполнить все ведомости по клиенту',
      start: '2022-12-14T12:54',
      end: '2022-12-30T12:54',
      progress_status: 'Принята',
      status: null,
      creator_id: 1,
      worker_id: 1,
      order_id: null,
      client_id: 3,
      company_id: 1,
      closed_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      task_type: 'ordered',
      title: 'Обзвон',
      content: 'Прозвонить все лиды',
      start: '2022-12-10T12:00',
      end: '2022-12-15T12:00',
      progress_status: 'Новая',
      status: null,
      creator_id: 1,
      worker_id: 2,
      order_id: null,
      client_id: 4,
      company_id: 1,
      closed_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      task_type: 'ordered',
      title: 'Документы',
      content: 'Собрать все документы по клиенту',
      start: '2022-12-14T12:00',
      end: '2022-12-30T12:00',
      progress_status: 'Выполняется',
      status: null,
      creator_id: 1,
      worker_id: 3,
      order_id: null,
      client_id: 6,
      company_id: 1,
      closed_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      task_type: 'ordered',
      title: 'Доп. услуги',
      content: 'Подключить клиенту доп.функционал',
      start: '2022-12-14T12:00',
      end: '2022-12-30T12:00',
      progress_status: 'Согласование',
      status: null,
      creator_id: 1,
      worker_id: 5,
      order_id: null,
      client_id: 7,
      company_id: 1,
      closed_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      task_type: 'personal',
      title: 'Прозвон',
      content: 'Позвонить клиенту',
      start: '2022-12-14T12:00',
      end: '2022-12-15T12:00',
      progress_status: 'Принята',
      status: null,
      creator_id: 1,
      worker_id: 1,
      order_id: null,
      client_id: 8,
      company_id: 1,
      closed_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      task_type: 'personal',
      title: 'Доп. соглашение',
      content: 'Заполнить с клиентом доп.соглашение',
      start: '2022-12-14T12:00',
      end: '2022-12-20T12:00',
      progress_status: 'Принята',
      status: null,
      creator_id: 3,
      worker_id: 3,
      order_id: null,
      client_id: 5,
      company_id: 1,
      closed_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      task_type: 'personal',
      title: 'Знакомство',
      content: 'Назначить встречу с клиентом',
      start: '2022-12-14T12:54',
      end: '2022-12-30T12:54',
      progress_status: 'Выполняется',
      status: null,
      creator_id: 3,
      worker_id: 3,
      order_id: null,
      client_id: 3,
      company_id: 1,
      closed_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      task_type: 'ordered',
      title: 'Документы',
      content: 'Принять у клиента документы',
      start: '2022-12-14T12:00',
      end: '2022-12-20T12:00',
      progress_status: 'Принята',
      status: null,
      creator_id: 5,
      worker_id: 2,
      order_id: null,
      client_id: 2,
      company_id: 1,
      closed_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      task_type: 'ordered',
      title: 'Срочно',
      content: 'Заключить договор',
      start: '2022-12-14T12:00',
      end: '2022-12-15T12:00',
      progress_status: 'Выполняется',
      status: null,
      creator_id: 1,
      worker_id: 6,
      order_id: null,
      client_id: 10,
      company_id: 1,
      closed_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      task_type: 'personal',
      title: 'Отчёт',
      content: 'Проверить отчёт',
      start: '2022-12-14T12:00',
      end: '2022-12-30T12:00',
      progress_status: 'Принята',
      status: null,
      creator_id: 4,
      worker_id: 4,
      order_id: null,
      client_id: 1,
      company_id: 1,
      closed_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    ], {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Tasks', null, {});
  },
};
