const bcrypt = require('bcrypt');

module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Workers', [{
      avatar: null,
      login: 'Миша',
      password: await bcrypt.hash('123', 10),
      name: 'Миша',
      second_name: 'Иванов',
      patronymic: 'Иванович',
      category_id: '2',
      company_id: '1',
      email: '123@123',
      phone: '89223762435',
      accepted: 'true',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      avatar: null,
      login: 'Admin',
      password: await bcrypt.hash('123', 10),
      name: 'Владимир',
      second_name: 'Пупкин',
      patronymic: 'Владимирович',
      category_id: '1',
      company_id: '1',
      email: '123@123',
      phone: '89226743524',
      accepted: 'true',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      avatar: null,
      login: 'AUP',
      password: await bcrypt.hash('123', 10),
      name: 'Вася',
      second_name: 'Васильев',
      patronymic: 'Васильевич',
      category_id: '2',
      company_id: '1',
      email: '123@123',
      phone: '8925642347',
      accepted: 'true',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      avatar: null,
      login: 'Кама',
      password: await bcrypt.hash('123', 10),
      name: 'Камиль',
      second_name: 'Якупов',
      patronymic: 'Маратович',
      category_id: '2',
      company_id: '1',
      email: '123@123',
      phone: '89222683654',
      accepted: 'true',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      avatar: null,
      login: 'Влад',
      password: await bcrypt.hash('123', 10),
      name: 'Владислав',
      second_name: 'Дрегин',
      patronymic: 'Александрович',
      category_id: '2',
      company_id: '1',
      email: '123@123',
      phone: '89225678367',
      accepted: 'true',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      avatar: null,
      login: 'Маша',
      password: await bcrypt.hash('123', 10),
      name: 'Мария',
      second_name: 'Шелехова',
      patronymic: 'Викторовна',
      category_id: '2',
      company_id: '1',
      email: '123@123',
      phone: '89227834589',
      accepted: 'true',
      createdAt: new Date(),
      updatedAt: new Date(),
    }
    ], {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Workers', null, {});
  },
};
