export const USER = {
  USER_SIGNIN_START: 'USER_SIGNIN_START',
  USER_SIGNIN: 'USER_SIGNIN',
  USER_SIGNIN_ERROR: 'USER_SIGNIN_ERROR',
  USER_SIGNOUT: 'USER_SIGNOUT',
  USER_AUTH_START: 'USER_AUTH_START',
};

export const GLOBAL = {
  SET_LOADING: 'SET_LOADING',
};
